---
- name: Install and Configure Nerd Fonts - JetBrainMono
  hosts: '{{ target_hosts | d([]) }}'
  tasks:

    - name: Check for fontconfig
      ansible.builtin.apt:
        name: fontconfig
        state: present
        update_cache: true
      become: true

    - name: Install fonts-jetbrains-mono
      ansible.builtin.apt:
        name: fonts-jetbrains-mono
        state: present
        update_cache: true
      become: true
      register: install_result

    # - name: Echo install_result
    #   ansible.builtin.debug:
    #     msg:
    #       - "my_output is {{ install_result.failed }}"

    - name: Update font cache
      ansible.builtin.shell:
        cmd: "fc-cache -fv"
        executable: /bin/sh
      become: true
      changed_when: install_result.failed == 'False'
