---
- name: Install core vm apps
  hosts: '{{ target_hosts | d([]) }}'
  become: true
  tasks:

    - name: Run apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install core packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - unzip
          - nmap
          - yadm
          - htop
        update_cache: false

    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
