---
- name: Install latest qemu-guest-agent
  hosts: '{{ target_hosts | d([]) }}'
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true

    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
      become: true
