---
- name: Install core apps
  hosts: '{{ target_hosts | d([]) }}'
  become: true
  tasks:

    - name: Install core packages
      ansible.builtin.apt:
        name:
          - unzip
          - nmap
          - yadm
          - htop
        update_cache: true
